/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.ControllerAdditionalData;
import Dao.DaoArchive;
import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bruno
 */
public class ViewPrincipal extends javax.swing.JFrame {

    ControllerAdditionalData additionalData = new ControllerAdditionalData();
    int choseDate;    
    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelLogo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TabbedPaneInformacoes = new javax.swing.JTabbedPane();
        PanelDadosPrincipais = new javax.swing.JPanel();
        panel_anexar_aquivo_csv = new javax.swing.JPanel();
        btnChooseFile = new javax.swing.JButton();
        lbl_File_Path = new javax.swing.JLabel();
        lbl_validatoricon = new javax.swing.JLabel();
        lbl_title_anexar_aquivo = new javax.swing.JLabel();
        panel_additional_data = new javax.swing.JPanel();
        lbl_title_additional_data = new javax.swing.JLabel();
        lbl_registration_additional_data = new javax.swing.JLabel();
        lbl_user_additional_data = new javax.swing.JLabel();
        lbl_team_id_additional_data = new javax.swing.JLabel();
        lbl_indicator_additional_data = new javax.swing.JLabel();
        txt_user_additional_data = new javax.swing.JTextField();
        txt_registration_additional_data = new javax.swing.JTextField();
        txt_team_id_additional_data = new javax.swing.JTextField();
        check_delayed_actions = new javax.swing.JCheckBox();
        check_training_compliance = new javax.swing.JCheckBox();
        lbl_team_name_additional_data = new javax.swing.JLabel();
        txt_team_name_additional_data = new javax.swing.JTextField();
        btn_save = new javax.swing.JButton();
        lbl_mensage_error_registration = new javax.swing.JLabel();
        lbl_mensage_error_user = new javax.swing.JLabel();
        lbl_mensage_error_team_id = new javax.swing.JLabel();
        lbl_email_additional_data = new javax.swing.JLabel();
        txt_user_asana_additional_data = new javax.swing.JTextField();
        cb_months_additional_data = new javax.swing.JComboBox<>();
        lbl_months_additional_data = new javax.swing.JLabel();
        lbl_mensage_error_email = new javax.swing.JLabel();
        lbl_status_file = new javax.swing.JLabel();
        lbl_error_mes = new javax.swing.JLabel();
        PanelListagemDadosCSV = new javax.swing.JPanel();
        ScrollPane_listData = new javax.swing.JScrollPane();
        table_list_data = new javax.swing.JTable();
        btn_export = new javax.swing.JButton();
        btn_refresh_list = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bernhope");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        PanelLogo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo-bernhoeft-compressor.jpg"))); // NOI18N

        javax.swing.GroupLayout PanelLogoLayout = new javax.swing.GroupLayout(PanelLogo);
        PanelLogo.setLayout(PanelLogoLayout);
        PanelLogoLayout.setHorizontalGroup(
            PanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelLogoLayout.setVerticalGroup(
            PanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(27, 27, 27))
        );

        TabbedPaneInformacoes.setBackground(new java.awt.Color(255, 255, 255));
        TabbedPaneInformacoes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TabbedPaneInformacoesFocusGained(evt);
            }
        });
        TabbedPaneInformacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabbedPaneInformacoesMouseClicked(evt);
            }
        });

        PanelDadosPrincipais.setBackground(new java.awt.Color(255, 255, 255));

        panel_anexar_aquivo_csv.setBackground(new java.awt.Color(255, 255, 255));
        panel_anexar_aquivo_csv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 70, 152)));
        panel_anexar_aquivo_csv.setToolTipText("Teste");
        panel_anexar_aquivo_csv.setName("Teste"); // NOI18N

        btnChooseFile.setText("Escolha Arquivo");
        btnChooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseFileActionPerformed(evt);
            }
        });

        lbl_File_Path.setText("Nenhum arquivo selecionado...");

        lbl_validatoricon.setText("nada");

        lbl_title_anexar_aquivo.setBackground(new java.awt.Color(0, 70, 152));
        lbl_title_anexar_aquivo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_title_anexar_aquivo.setText("Anexar arquivo");

        javax.swing.GroupLayout panel_anexar_aquivo_csvLayout = new javax.swing.GroupLayout(panel_anexar_aquivo_csv);
        panel_anexar_aquivo_csv.setLayout(panel_anexar_aquivo_csvLayout);
        panel_anexar_aquivo_csvLayout.setHorizontalGroup(
            panel_anexar_aquivo_csvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_anexar_aquivo_csvLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_anexar_aquivo_csvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_anexar_aquivo_csvLayout.createSequentialGroup()
                        .addComponent(btnChooseFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_File_Path, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_anexar_aquivo_csvLayout.createSequentialGroup()
                        .addComponent(lbl_title_anexar_aquivo)
                        .addGap(684, 684, 684)))
                .addGap(259, 259, 259)
                .addComponent(lbl_validatoricon)
                .addContainerGap())
        );
        panel_anexar_aquivo_csvLayout.setVerticalGroup(
            panel_anexar_aquivo_csvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_anexar_aquivo_csvLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_title_anexar_aquivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_anexar_aquivo_csvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChooseFile)
                    .addComponent(lbl_File_Path)
                    .addComponent(lbl_validatoricon))
                .addContainerGap())
        );

        lbl_validatoricon.getAccessibleContext().setAccessibleName("");

        panel_additional_data.setBackground(new java.awt.Color(255, 255, 255));
        panel_additional_data.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 70, 152)));

        lbl_title_additional_data.setBackground(new java.awt.Color(0, 70, 152));
        lbl_title_additional_data.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_title_additional_data.setText("Dados Adicionais");

        lbl_registration_additional_data.setText("*Matricular:");

        lbl_user_additional_data.setText("*Usuário:");

        lbl_team_id_additional_data.setText("*Equipe ID:");

        lbl_indicator_additional_data.setText("*Indicadores:");

        txt_user_additional_data.setText("425");
        txt_user_additional_data.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_user_additional_dataFocusLost(evt);
            }
        });

        txt_registration_additional_data.setText("dfgbdgvbsffvaed");
        txt_registration_additional_data.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_registration_additional_dataFocusLost(evt);
            }
        });

        txt_team_id_additional_data.setText("70");
        txt_team_id_additional_data.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_team_id_additional_dataFocusLost(evt);
            }
        });

        check_delayed_actions.setSelected(true);
        check_delayed_actions.setText("% Ações Atrasadas");

        check_training_compliance.setSelected(true);
        check_training_compliance.setText("Cumprimento do treinamento JEDI");

        lbl_team_name_additional_data.setText("Equipe Nome:");

        txt_team_name_additional_data.setText("Novos Vingadores");
        txt_team_name_additional_data.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_team_name_additional_dataFocusLost(evt);
            }
        });

        btn_save.setBackground(new java.awt.Color(0, 70, 152));
        btn_save.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_save.setForeground(new java.awt.Color(255, 255, 255));
        btn_save.setText("Salvar");
        btn_save.setEnabled(false);
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        lbl_mensage_error_registration.setForeground(new java.awt.Color(255, 51, 0));

        lbl_mensage_error_user.setForeground(new java.awt.Color(255, 51, 0));

        lbl_mensage_error_team_id.setForeground(new java.awt.Color(255, 51, 0));

        lbl_email_additional_data.setText("*Usuário Asana:");

        txt_user_asana_additional_data.setText("arthur42phg@gmail.com");
        txt_user_asana_additional_data.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_user_asana_additional_dataFocusLost(evt);
            }
        });
        txt_user_asana_additional_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_user_asana_additional_dataActionPerformed(evt);
            }
        });

        cb_months_additional_data.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha Mês", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        cb_months_additional_data.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_months_additional_dataItemStateChanged(evt);
            }
        });
        cb_months_additional_data.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cb_months_additional_dataFocusLost(evt);
            }
        });

        lbl_months_additional_data.setText("*Mês");

        lbl_mensage_error_email.setForeground(new java.awt.Color(255, 51, 0));

        lbl_status_file.setBackground(new java.awt.Color(255, 255, 255));
        lbl_status_file.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N

        lbl_error_mes.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout panel_additional_dataLayout = new javax.swing.GroupLayout(panel_additional_data);
        panel_additional_data.setLayout(panel_additional_dataLayout);
        panel_additional_dataLayout.setHorizontalGroup(
            panel_additional_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_additional_dataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_additional_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_additional_dataLayout.createSequentialGroup()
                        .addGroup(panel_additional_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_team_id_additional_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_user_additional_data, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_additional_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_mensage_error_team_id, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_additional_dataLayout.createSequentialGroup()
                                .addGroup(panel_additional_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_team_id_additional_data, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panel_additional_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lbl_mensage_error_user, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_user_additional_data, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                                    .addComponent(lbl_mensage_error_registration, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(panel_additional_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_additional_dataLayout.createSequentialGroup()
                                        .addComponent(lbl_months_additional_data, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cb_months_additional_data, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_error_mes)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(panel_additional_dataLayout.createSequentialGroup()
                                        .addGroup(panel_additional_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_email_additional_data)
                                            .addComponent(lbl_team_name_additional_data, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(panel_additional_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_team_name_additional_data, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_user_asana_additional_data, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_mensage_error_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(434, 434, 434))))
                    .addGroup(panel_additional_dataLayout.createSequentialGroup()
                        .addGroup(panel_additional_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(check_training_compliance)
                            .addComponent(check_delayed_actions)
                            .addComponent(lbl_indicator_additional_data)
                            .addComponent(btn_save)
                            .addGroup(panel_additional_dataLayout.createSequentialGroup()
                                .addComponent(lbl_registration_additional_data)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_registration_additional_data, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_title_additional_data)))
                        .addGap(431, 431, 431))))
            .addGroup(panel_additional_dataLayout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(lbl_status_file)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_additional_dataLayout.setVerticalGroup(
            panel_additional_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_additional_dataLayout.createSequentialGroup()
                .addGroup(panel_additional_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_additional_dataLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(panel_additional_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_registration_additional_data)
                            .addComponent(txt_registration_additional_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_mensage_error_registration)
                        .addGap(4, 4, 4)
                        .addGroup(panel_additional_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_user_additional_data)
                            .addComponent(txt_user_additional_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(lbl_mensage_error_user)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_additional_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_team_id_additional_data)
                            .addComponent(txt_team_id_additional_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_mensage_error_team_id))
                    .addGroup(panel_additional_dataLayout.createSequentialGroup()
                        .addComponent(lbl_title_additional_data)
                        .addGap(31, 31, 31)
                        .addGroup(panel_additional_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_months_additional_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_months_additional_data)
                            .addComponent(lbl_error_mes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_additional_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_email_additional_data)
                            .addComponent(txt_user_asana_additional_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_mensage_error_email)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_additional_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_team_name_additional_data)
                            .addComponent(txt_team_name_additional_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_indicator_additional_data)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(check_delayed_actions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(check_training_compliance)
                .addGap(18, 18, 18)
                .addComponent(btn_save)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(lbl_status_file)
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout PanelDadosPrincipaisLayout = new javax.swing.GroupLayout(PanelDadosPrincipais);
        PanelDadosPrincipais.setLayout(PanelDadosPrincipaisLayout);
        PanelDadosPrincipaisLayout.setHorizontalGroup(
            PanelDadosPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDadosPrincipaisLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelDadosPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_anexar_aquivo_csv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_additional_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelDadosPrincipaisLayout.setVerticalGroup(
            PanelDadosPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDadosPrincipaisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_anexar_aquivo_csv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel_additional_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        panel_anexar_aquivo_csv.getAccessibleContext().setAccessibleName("");

        TabbedPaneInformacoes.addTab("Dados Principais", PanelDadosPrincipais);

        PanelListagemDadosCSV.setBackground(new java.awt.Color(255, 255, 255));

        table_list_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricula", "Usuário", "Equipe Id", "Equipe Nome", "Indicador Id", "Indicador Nome", "Valor", "Mês", "Ano"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScrollPane_listData.setViewportView(table_list_data);

        btn_export.setBackground(new java.awt.Color(0, 70, 152));
        btn_export.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_export.setForeground(new java.awt.Color(255, 255, 255));
        btn_export.setText("Exportar CSV");
        btn_export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exportActionPerformed(evt);
            }
        });

        btn_refresh_list.setBackground(new java.awt.Color(0, 70, 152));
        btn_refresh_list.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_refresh_list.setForeground(new java.awt.Color(255, 255, 255));
        btn_refresh_list.setText("Atualizar Lista");
        btn_refresh_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refresh_listActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelListagemDadosCSVLayout = new javax.swing.GroupLayout(PanelListagemDadosCSV);
        PanelListagemDadosCSV.setLayout(PanelListagemDadosCSVLayout);
        PanelListagemDadosCSVLayout.setHorizontalGroup(
            PanelListagemDadosCSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelListagemDadosCSVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelListagemDadosCSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPane_listData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1122, Short.MAX_VALUE)
                    .addGroup(PanelListagemDadosCSVLayout.createSequentialGroup()
                        .addComponent(btn_export)
                        .addGap(18, 18, 18)
                        .addComponent(btn_refresh_list)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelListagemDadosCSVLayout.setVerticalGroup(
            PanelListagemDadosCSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelListagemDadosCSVLayout.createSequentialGroup()
                .addGroup(PanelListagemDadosCSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_export)
                    .addComponent(btn_refresh_list))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(ScrollPane_listData, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        TabbedPaneInformacoes.addTab("Listagem dos Dados", PanelListagemDadosCSV);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TabbedPaneInformacoes)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabbedPaneInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TabbedPaneInformacoes.getAccessibleContext().setAccessibleName("Dados Principais");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseFileActionPerformed
        File[] files = null; 
        JFileChooser filechoose = new JFileChooser(); 
        filechoose.setDialogTitle("Escolha o arquivo..."); 
        filechoose.setDialogType(JFileChooser.OPEN_DIALOG); 
        filechoose.setApproveButtonText("OK"); 
        filechoose.setFileSelectionMode(JFileChooser.FILES_ONLY); 
        filechoose.setMultiSelectionEnabled(true); 
        int resultado = filechoose.showOpenDialog(filechoose); 
        if (resultado == JFileChooser.CANCEL_OPTION){ 
            filechoose.setDialogType(JFileChooser.SAVE_DIALOG);            
        } 
        files = filechoose.getSelectedFiles(); 
        for(File file : files){
                lbl_File_Path.setText(file.getPath());                
        }       
    }//GEN-LAST:event_btnChooseFileActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
       int resultImport = 1;
        String filePath = lbl_File_Path.getText();
        try {
            lbl_validatoricon.setText(additionalData.validFileImport(filePath));
            
            if (txt_registration_additional_data.getText().equals("")) {errorRegistration("Campo não poder estar vazio");}else{errorRegistration("");}
            if (txt_user_additional_data.getText().equals("")) {errorUser("Campo não poder estar vazio");}else{errorUser("");}
            if (txt_team_id_additional_data.getText().equals("")) {errorTeamId("Campo não poder estar vazio");}else{errorTeamId("");}
            if (txt_user_asana_additional_data.getText().equals("")) {errorEmail("Campo não poder estar vazio");}else{errorEmail("");}
            if (choseDate != 0) {                
                additionalData.validAdditionalData(txt_registration_additional_data.getText(),
                                                  txt_user_additional_data.getText(),
                                                  txt_team_id_additional_data.getText(),
                                                  txt_team_name_additional_data.getText(),
                                                  txt_user_asana_additional_data.getText(),
                                                  cb_months_additional_data.getSelectedIndex(),
                                                  check_delayed_actions.isSelected(),
                                                  check_training_compliance.isSelected());
                resultImport = additionalData.addDataArrayStudents(filePath);   
                if (resultImport > 0) {
                    cleanFields(JOptionPane.showConfirmDialog(null,
                                          "Sua Planilha foi importada com sucesso!\n Deseja Incluir um novo usuário?",
                                          "Atenção",
                                          JOptionPane.OK_OPTION,
                                          JOptionPane.CANCEL_OPTION));
                }else{
                    JOptionPane.showMessageDialog(null, "Usuário não encontrado, \n tente com o email do Asana.");
                    txt_user_asana_additional_data.requestFocus();
                }                                                
            }else{
                lbl_error_mes.setText("Campo Obrigatorio!");
            }                                 
            
        } catch (IOException ex) {
            Logger.getLogger(ViewPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(ViewPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }       
    }//GEN-LAST:event_btn_saveActionPerformed

    public void cleanFields(int result){
        
        if(result == 0){
            txt_registration_additional_data.requestFocus();
            txt_registration_additional_data.setText("");
            txt_user_additional_data.setText("");
            txt_team_id_additional_data.setText("");
            txt_team_name_additional_data.setText("");
            txt_user_asana_additional_data.setText("");
            cb_months_additional_data.setSelectedIndex(0);
        }else{
            TabbedPaneInformacoes.setSelectedIndex(1);
        }
    }
    
    private void txt_registration_additional_dataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_registration_additional_dataFocusLost
        filledFields();
    }//GEN-LAST:event_txt_registration_additional_dataFocusLost

    private void txt_user_additional_dataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_user_additional_dataFocusLost
        filledFields();
    }//GEN-LAST:event_txt_user_additional_dataFocusLost

    private void txt_team_id_additional_dataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_team_id_additional_dataFocusLost
        filledFields();
    }//GEN-LAST:event_txt_team_id_additional_dataFocusLost

    private void txt_user_asana_additional_dataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_user_asana_additional_dataFocusLost
        filledFields();
    }//GEN-LAST:event_txt_user_asana_additional_dataFocusLost

    private void txt_user_asana_additional_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_user_asana_additional_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_user_asana_additional_dataActionPerformed

    private void cb_months_additional_dataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cb_months_additional_dataFocusLost
        // TODO add your handling code here:        
        filledFields();
    }//GEN-LAST:event_cb_months_additional_dataFocusLost

    private void btn_exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exportActionPerformed
        // TODO add your handling code here:
        //Chamar o metódo para exportar os datos               
        additionalData.exportDataTableForExcelCSV();
    }//GEN-LAST:event_btn_exportActionPerformed

    private void TabbedPaneInformacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabbedPaneInformacoesMouseClicked
        // TODO add your handling code here:  
        //Execultada quando a Aba 2 do panel é clicada        
    }//GEN-LAST:event_TabbedPaneInformacoesMouseClicked

    private void TabbedPaneInformacoesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TabbedPaneInformacoesFocusGained
        
    }//GEN-LAST:event_TabbedPaneInformacoesFocusGained

    private void btn_refresh_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refresh_listActionPerformed
        // TODO add your handling code here:                
        DefaultTableModel modelTableListFarol = (DefaultTableModel) table_list_data.getModel();
        if (modelTableListFarol.getRowCount() > 0) {
            additionalData.deleteDataListForTabel(modelTableListFarol);   
        }        
        modelTableListFarol = additionalData.getDataListForTabel(modelTableListFarol);
    }//GEN-LAST:event_btn_refresh_listActionPerformed

    private void txt_team_name_additional_dataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_team_name_additional_dataFocusLost
        // TODO add your handling code here:
        filledFields();
    }//GEN-LAST:event_txt_team_name_additional_dataFocusLost

    private void cb_months_additional_dataItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_months_additional_dataItemStateChanged
        // TODO add your handling code here:        
        choseDate = cb_months_additional_data.getSelectedIndex();
        lbl_error_mes.setText("");        
    }//GEN-LAST:event_cb_months_additional_dataItemStateChanged

    public void filledFields(){
        if (lbl_File_Path.getText().equals("Nenhum arquivo selecionado...")) {
            JOptionPane.showMessageDialog(null, "Selecione o arquivo CSV!");
        }        
        if (txt_registration_additional_data.getText().equals("")) {
            errorRegistration("Campo não poder estar vazio");
        }else{
            errorRegistration("");
        }
        if (txt_user_additional_data.getText().equals("")) {
            errorUser("Campo não poder estar vazio");
        }else{
            errorUser("");
        }
        if (txt_team_id_additional_data.getText().equals("")) {
            errorTeamId("Campo não poder estar vazio");
        }else{
            errorTeamId("");
        }
        if (txt_user_asana_additional_data.getText().equals("")) {
            errorEmail("Campo não poder estar vazio");
        }else{
            errorEmail("");
        }
        if (choseDate == 0) {
            lbl_error_mes.setText("Campo Obrigatorio!");
        }else{
            lbl_error_mes.setText("");
        }
        if (!txt_registration_additional_data.getText().equals("")&&
            !txt_user_additional_data.getText().equals("") && 
            !txt_team_id_additional_data.getText().equals("") &&
            !txt_user_asana_additional_data.getText().equals("") &&
             choseDate != 0) {
            btn_save.setEnabled(true);
        }
    }
    
    public void errorRegistration(String error){
        lbl_mensage_error_registration.setText(error);
    }
    public void errorUser(String error){
        lbl_mensage_error_user.setText(error);
    }
    public void errorTeamId(String error){
        lbl_mensage_error_team_id.setText(error);
    }
    public void errorEmail(String error){
        lbl_mensage_error_email.setText(error);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDadosPrincipais;
    private javax.swing.JPanel PanelListagemDadosCSV;
    private javax.swing.JPanel PanelLogo;
    private javax.swing.JScrollPane ScrollPane_listData;
    private javax.swing.JTabbedPane TabbedPaneInformacoes;
    private javax.swing.JButton btnChooseFile;
    private javax.swing.JButton btn_export;
    private javax.swing.JButton btn_refresh_list;
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> cb_months_additional_data;
    private javax.swing.JCheckBox check_delayed_actions;
    private javax.swing.JCheckBox check_training_compliance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_File_Path;
    private javax.swing.JLabel lbl_email_additional_data;
    private javax.swing.JLabel lbl_error_mes;
    private javax.swing.JLabel lbl_indicator_additional_data;
    private javax.swing.JLabel lbl_mensage_error_email;
    private javax.swing.JLabel lbl_mensage_error_registration;
    private javax.swing.JLabel lbl_mensage_error_team_id;
    private javax.swing.JLabel lbl_mensage_error_user;
    private javax.swing.JLabel lbl_months_additional_data;
    private javax.swing.JLabel lbl_registration_additional_data;
    private javax.swing.JLabel lbl_status_file;
    private javax.swing.JLabel lbl_team_id_additional_data;
    private javax.swing.JLabel lbl_team_name_additional_data;
    private javax.swing.JLabel lbl_title_additional_data;
    private javax.swing.JLabel lbl_title_anexar_aquivo;
    private javax.swing.JLabel lbl_user_additional_data;
    private javax.swing.JLabel lbl_validatoricon;
    private javax.swing.JPanel panel_additional_data;
    private javax.swing.JPanel panel_anexar_aquivo_csv;
    private javax.swing.JTable table_list_data;
    private javax.swing.JTextField txt_registration_additional_data;
    private javax.swing.JTextField txt_team_id_additional_data;
    private javax.swing.JTextField txt_team_name_additional_data;
    private javax.swing.JTextField txt_user_additional_data;
    private javax.swing.JTextField txt_user_asana_additional_data;
    // End of variables declaration//GEN-END:variables
}
